language: haskell
before_install:
env:
 - GHCVER=7.6.3 CABALVER=1.18
 - GHCVER=7.8.4 CABALVER=1.18
 - GHCVER=7.10.1 CABALVER=1.22
 - GHCVER=head  CABALVER=head

matrix:
  allow_failures:
   - env: GHCVER=7.6.3 CABALVER=1.18
   - env: GHCVER=7.10.1 CABALVER=1.22
   - env: GHCVER=head  CABALVER=head

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install libpcap-dev
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH
 - uname -r
# - sudo apt-get install linux-headers-2.6.32
 - cabal --version

install:
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests pfq-4.0.tar.gz

script:
 - pwd
 - tar xf pfq-4.0.tar.gz
 - tar xf PFQ.tar.bz2
 - cd PFQ
 - sudo cp kernel/linux/* /usr/include/linux/
 - cd /home/travis/build/tolysz/hans-pfq && cd PFQ/user/C && make && sudo make install
 - cd /home/travis/build/tolysz/hans-pfq && cd PFQ/user/Haskell && cabal configure --enable-tests && cabal install
 - cabal install
 # pfq is intalled time for hans-pfq
 - cd /home/travis/build/tolysz/hans-pfq
 - cabal install --only-dependencies
 - cabal configure --enable-tests
 - cabal build
 - cabal test

# - runhaskell Build.hs install
#  --enable-library-coverage || cabal configure --enable-tests --enable-coverage
# - cabal build
# - cabal test

#after_script:
# - cabal install hpc-coveralls
# - hpc-coveralls --exclude-dir=test test
